### ISSUE TITLE
search.organisation table isn't distinct on name

### ISSUE THREAD

**Issue by nacnudus** [alphagov/govuk-knowledge-graph-gcp#481]
Some organisations, such as https://www.gov.uk/api/content/government/organisations/animal-and-plant-health-agency, appear multiple times in the search.organisation table, seemingly because they have multiple parent organisations.  The parent organisation column ought to be an array type instead.  If we fix this, we'll need to check that it renders correctly in the GovSearch app, and also check any queries there that reference this table.

https://github.com/alphagov/govuk-knowledge-graph-search/blob/31850dfe9a95c9388064d95ce3e421fb9f8a971d/bigquery.ts#LL75C1-L75C1

**Comment by j-marvin-GDS** [comment]
Closed by PR 526
